name: Daily Docker Build

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  # Build and push base multi-platform image
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL
          df -h

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push base multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: base
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.DATE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prune Docker
        run: |
          docker system prune -af
          df -h

  # Build AMD64 prebuilt image
  build-amd64-prebuilt:
    runs-on: ubuntu-latest
    needs: build-base
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL
          df -h

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push AMD64 prebuilt image 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prebuilt
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:prebuilt-amd64-${{ env.DATE }}
          cache-from: type=gha
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  # Build ARM64 prebuilt image
  build-arm64-prebuilt:
    runs-on: ubuntu-24.04-arm64
    needs: build-base
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL
          df -h

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ARM64 prebuilt image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prebuilt
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:prebuilt-arm64-${{ env.DATE }}
          cache-from: type=gha
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  # Merge prebuilt images into multi-platform image
  create-multiplatform-prebuilt:
    needs: [build-amd64-prebuilt, build-arm64-prebuilt]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and push multi-platform prebuilt manifest
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:prebuilt
            ghcr.io/${{ github.repository }}:prebuilt-${{ env.DATE }}
          provenance: false
          oci-mediatypes: true
          inputs: |
            type=registry,reference=ghcr.io/${{ github.repository }}:prebuilt-amd64-${{ env.DATE }},platform=linux/amd64
            type=registry,reference=ghcr.io/${{ github.repository }}:prebuilt-arm64-${{ env.DATE }},platform=linux/arm64